function validate_select(element,flag,message){if(element.selectedIndex==0)return update_error(false,element,flag,message);else
return update_error(true,element,flag,message);}function validate_email(element,flag,message){var regex=/^[\w.-]+@[\w.-]+\.[a-zA-Z]{2,4}$/;return update_error(regex.test(element.value),element,flag,message);}function validate_number(element,flag,message){var regex=/^([0-9\-])+$/;return update_error(regex.test(element.value),element,flag,message);}function validate_float(element,flag,message){var regex=/^[0-9]+(\.[0-9]+)?$/;return update_error(regex.test(alltrim(element.value)),element,flag,message);}function check_empty_space(element,flag,message){var regex1=/\s/;if(regex1.test(element.value))return update_error(false,element,flag,message);else
return update_error(true,element,flag,message);}function check_max_length(length,element,flag,message){if(element.value.length>length)return update_error(false,element,flag,message);else
return update_error(true,element,flag,message);}function restrict_email(element,flag,message){var regex=/^[\w.-]+@[\w.-]+\.[a-zA-Z]{2,4}$/;var check_regex=regex.test(element.value);if(check_regex==true)return update_error(false,element,flag,message);else
return update_error(true,element,flag,message);}function ltrim(str){return str.replace(/^\s+/,'');}function rtrim(str){return str.replace(/\s+$/,'');}function alltrim(str){return str.replace(/^\s+|\s+$/g,'');}function check_length(length,element,flag,message){if(element.value.length<length)return update_error(false,element,flag,message);else
return update_error(true,element,flag,message);}function check_text_empty(element,flag,message){if(element.value=="")return update_error(false,element,flag,message);else
return update_error(true,element,flag,message);}function match_text(element1,element2,flag,message){if(element1.value!=element2.value)return update_error(false,element2,flag,message);else
return update_error(true,element2,flag,message);}function validateUrl(element,flag,message){if(isUrl(element.value))return update_error(true,element,flag,message);else
return update_error(false,element,flag,message);}function isUrl(s){var regexp=/(ftp|http|https):\/\/(\w+:{0,1}\w*@)?(\S+)(:[0-9]+)?(\/|\/([\w#!:.?+=&%@!\-\/]))?/
return regexp.test(s);}function compare_dates(element1,element2,start_hour,start_minute,end_hour,end_minute,flag,message){var dt1=parseInt(element1.value.substring(3,5),10);var mon1=parseInt(element1.value.substring(0,2),10);var yr1=parseInt(element1.value.substring(6,10),10);var dt2=parseInt(element2.value.substring(3,5),10);var mon2=parseInt(element2.value.substring(0,2),10);var yr2=parseInt(element2.value.substring(6,10),10);var date1=new Date(yr1,mon1,dt1,start_hour.value,start_minute.value,00);var date2=new Date(yr2,mon2,dt2,end_hour.value,end_minute.value,00);if(date2<date1){return update_error(false,element2,flag,message);}else{return update_error(true,element2,flag,message);}}function validatePhoneNumber(element,flag,message){var phoneNumberPattern=/^\(?(\d{3})\)?[- ]?(\d{3})[- ]?(\d{4})$/;if(phoneNumberPattern.test(element.value)&&element.value!='')return update_error(true,element,flag,message);else
return update_error(false,element,flag,message);}function validate_creditcard(element1,element2,flag,message){var regex=/^([0-9\-])+$/;if(element1.value=="mastercard"||element1.value=="discover"){if(element2.value.length==16&&element2.value!=''&&regex.test(element2.value))return update_error(true,element2,flag,message);else
return update_error(false,element2,flag,message);}if(element1.value=="amex"){if(element2.value.length==15&&element2.value!=''&&regex.test(element2.value))return update_error(true,element2,flag,message);else
return update_error(false,element2,flag,message);}if(element1.value=="visa"){if((element2.value.length<13||element2.value.length>16)||element2.value==''||!regex.test(element2.value))return update_error(false,element2,flag,message);else
return update_error(true,element2,flag,message);}return update_error(false,element2,flag,message);}function validate_cvv(element1,element2,flag,message){var regex=/^([0-9\-])+$/;if(element1.value=="mastercard"||element1.value=="discover"||element1.value=="visa"){if(element2.value.length==3&&element2.value!=''&&regex.test(element2.value))return update_error(true,element2,flag,message);else
return update_error(false,element2,flag,message);}if(element1.value=="amex"){if(element2.value.length==4&&element2.value!=''&&regex.test(element2.value))return update_error(true,element2,flag,message);else
return update_error(false,element2,flag,message);}return update_error(false,element2,flag,message);}function update_error(state,element,flag,message){var img_postfix='_notification_img';amg=document.getElementById(element.name+img_postfix);if(state==false){element.title=message;element.style.backgroundColor=error_color;if(flag)element.focus();}else{element.title='';element.style.backgroundColor='';}if(state&&flag)return true;else
return false;}